import { copyFile, mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const expoDirectory = resolve(scriptDirectory, '..');
const clientDirectory = resolve(expoDirectory, '..', 'dist', 'client');
const embeddedAssetsDirectory = resolve(expoDirectory, 'embedded-assets');
const indexHtml = await readFile(resolve(clientDirectory, 'index.html'), 'utf8');

const scriptPath = indexHtml.match(/<script[^>]+src="([^"]+)"/)?.[1];
const stylePath = indexHtml.match(/<link[^>]+href="([^"]+\.css)"/)?.[1];

if (!scriptPath || !stylePath) {
  throw new Error('Could not locate the built Outlyride JavaScript and CSS files.');
}

let javascript = await readFile(resolve(clientDirectory, scriptPath.replace(/^\//, '')), 'utf8');
let stylesheet = await readFile(resolve(clientDirectory, stylePath.replace(/^\//, '')), 'utf8');

// System sans-serif fonts keep the embedded update much smaller than bundling every Roboto subset.
stylesheet = stylesheet.replace(/@font-face\{[^}]*\}/g, '');

const assetPaths = new Set(
  `${javascript}\n${stylesheet}`.match(/\/assets\/[A-Za-z0-9_./-]+/g) ?? [],
);

const mimeTypes = {
  '.gif': 'image/gif',
  '.jpeg': 'image/jpeg',
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
};

const homeAssetPaths = new Set([
  '/assets/outlyride/app-logo-transparent.png',
  '/assets/outlyride/bookings-signed-out-hero-v2.png',
  '/assets/outlyride/delivery-box.png',
  '/assets/outlyride/discover-together.png',
  '/assets/outlyride/header-city.png',
  '/assets/outlyride/ride-sedan.png',
  '/assets/android/navigation-bar.svg',
  '/assets/status/ios-status-icons.svg',
  '/assets/status/status-icons.svg',
]);
const transparentPixel = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
const bundledAssets = [];

for (const assetPath of assetPaths) {
  const isDiscoverArtwork =
    assetPath.startsWith('/assets/outlyride/events/') ||
    assetPath.startsWith('/assets/outlyride/places/') ||
    assetPath.startsWith('/assets/outlyride/stories/');

  if (!homeAssetPaths.has(assetPath) && !isDiscoverArtwork) {
    javascript = javascript.split(assetPath).join(transparentPixel);
    stylesheet = stylesheet.split(assetPath).join(transparentPixel);
    continue;
  }

  const localPath = resolve(clientDirectory, assetPath.replace(/^\//, ''));

  try {
    if (!(await stat(localPath)).isFile()) continue;
  } catch {
    continue;
  }

  const mimeType = mimeTypes[extname(localPath).toLowerCase()] ?? 'application/octet-stream';

  // Keep large raster images outside the JavaScript update. Embedding them as base64 made
  // the Android development bundle exceed 10 MB and unreliable over an Expo tunnel.
  if (mimeType.startsWith('image/') && mimeType !== 'image/svg+xml') {
    const assetName = assetPath.replace(/^\/assets\//, '').replaceAll('/', '--');
    const destinationPath = resolve(embeddedAssetsDirectory, assetName);
    const placeholder = `__OUTLYRIDE_ASSET_${bundledAssets.length}__`;

    await mkdir(embeddedAssetsDirectory, { recursive: true });
    await copyFile(localPath, destinationPath);
    javascript = javascript.split(assetPath).join(placeholder);
    stylesheet = stylesheet.split(assetPath).join(placeholder);
    bundledAssets.push({ placeholder, requirePath: `./embedded-assets/${assetName}` });
    continue;
  }

  const encodedAsset = (await readFile(localPath)).toString('base64');
  const dataUrl = `data:${mimeType};base64,${encodedAsset}`;
  javascript = javascript.split(assetPath).join(dataUrl);
  stylesheet = stylesheet.split(assetPath).join(dataUrl);
}

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <meta name="theme-color" content="#079b34" />
    <style>${stylesheet}</style>
  </head>
  <body>
    <div id="root"></div>
    <script>${javascript.replace(/<\/script/gi, '<\\/script')}</script>
  </body>
</html>`;

const assetEntries = bundledAssets
  .map(
    ({ placeholder, requirePath }) =>
      `  [${JSON.stringify(placeholder)}, Image.resolveAssetSource(require(${JSON.stringify(requirePath)})).uri],`,
  )
  .join('\n');
const generatedModule = `// Generated by scripts/embed-web-app.mjs. Do not edit by hand.\nimport { Image } from 'react-native';\n\nconst htmlTemplate = ${JSON.stringify(html)};\nconst assetUrls: Array<[string, string]> = [\n${assetEntries}\n];\n\nexport const embeddedOutlyrideHtml = assetUrls.reduce(\n  (value, [placeholder, url]) => value.split(placeholder).join(url),\n  htmlTemplate,\n);\n`;
await writeFile(resolve(expoDirectory, 'embeddedOutlyride.ts'), generatedModule);

console.log(
  `Embedded Outlyride UI (${Math.round(Buffer.byteLength(html) / 1024)} KB HTML, ${bundledAssets.length} Metro assets).`,
);
