import { readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const expoDirectory = resolve(scriptDirectory, '..');
const clientDirectory = resolve(expoDirectory, '..', 'dist', 'client');
const indexHtml = await readFile(resolve(clientDirectory, 'index.html'), 'utf8');

const scriptPath = indexHtml.match(/<script[^>]+src="([^"]+)"/)?.[1];
const stylePath = indexHtml.match(/<link[^>]+href="([^"]+\.css)"/)?.[1];

if (!scriptPath || !stylePath) {
  throw new Error('Could not locate the built Outlyride JavaScript and CSS files.');
}

let javascript = await readFile(resolve(clientDirectory, scriptPath.replace(/^\//, '')), 'utf8');
let stylesheet = await readFile(resolve(clientDirectory, stylePath.replace(/^\//, '')), 'utf8');

// System sans-serif fonts keep the embedded update much smaller than bundling every Roboto subset.
stylesheet = stylesheet.replace(/@font-face\{[^}]*\}/g, '');

const assetPaths = new Set(
  `${javascript}\n${stylesheet}`.match(/\/assets\/[A-Za-z0-9_./-]+/g) ?? [],
);

const mimeTypes = {
  '.gif': 'image/gif',
  '.jpeg': 'image/jpeg',
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
};

const homeAssetPaths = new Set([
  '/assets/outlyride/app-logo-transparent.png',
  '/assets/outlyride/bookings-signed-out-hero-v2.png',
  '/assets/outlyride/delivery-box.png',
  '/assets/outlyride/discover-together.png',
  '/assets/outlyride/header-city.png',
  '/assets/outlyride/onboarding-account.png',
  '/assets/outlyride/onboarding-driver.png',
  '/assets/outlyride/onboarding-passenger.png',
  '/assets/outlyride/onboarding-travel.png',
  '/assets/outlyride/outlyride-logo-v2.png',
  '/assets/outlyride/ride-sedan.png',
  '/assets/android/navigation-bar.svg',
  '/assets/status/ios-status-icons.svg',
  '/assets/status/status-icons.svg',
]);
const transparentPixel = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
let embeddedImageCount = 0;

for (const assetPath of assetPaths) {
  const isDiscoverArtwork =
    assetPath.startsWith('/assets/outlyride/events/') ||
    assetPath.startsWith('/assets/outlyride/places/') ||
    assetPath.startsWith('/assets/outlyride/stories/') ||
    assetPath.startsWith('/assets/outlyride/offers/');

  if (!homeAssetPaths.has(assetPath) && !isDiscoverArtwork) {
    javascript = javascript.split(assetPath).join(transparentPixel);
    stylesheet = stylesheet.split(assetPath).join(transparentPixel);
    continue;
  }

  const localPath = resolve(clientDirectory, assetPath.replace(/^\//, ''));

  if (!(await stat(localPath)).isFile()) {
    throw new Error(`Outlyride asset is not a file: ${assetPath}`);
  }

  const mimeType = mimeTypes[extname(localPath).toLowerCase()] ?? 'application/octet-stream';

  // Android release builds resolve React Native images to drawable resource names,
  // not URLs a WebView can load. Inline size-limited WebP images so Android and iOS
  // can render the same offline artwork without a file:// origin or network server.
  if (mimeType.startsWith('image/') && mimeType !== 'image/svg+xml') {
    const encodedAsset = await sharp(localPath)
      // Discover cards are rendered at roughly 300px wide on phones. Keeping
      // the offline source near that density avoids WebView memory pressure.
      .resize({ width: 600, height: 600, fit: 'inside', withoutEnlargement: true })
      .webp({ quality: 60, effort: 5 })
      .toBuffer();
    const dataUrl = `data:image/webp;base64,${encodedAsset.toString('base64')}`;
    javascript = javascript.split(assetPath).join(dataUrl);
    stylesheet = stylesheet.split(assetPath).join(dataUrl);
    embeddedImageCount += 1;
    continue;
  }

  const encodedAsset = (await readFile(localPath)).toString('base64');
  const dataUrl = `data:${mimeType};base64,${encodedAsset}`;
  javascript = javascript.split(assetPath).join(dataUrl);
  stylesheet = stylesheet.split(assetPath).join(dataUrl);
}

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <meta name="theme-color" content="#079b34" />
    <style>${stylesheet}</style>
  </head>
  <body>
    <div id="root"></div>
    <script>${javascript.replace(/<\/script/gi, '<\\/script')}</script>
  </body>
</html>`;

const htmlBytes = Buffer.byteLength(html);
if (htmlBytes > 8 * 1024 * 1024) {
  throw new Error(`Embedded Outlyride HTML is too large for a reliable update (${Math.round(htmlBytes / 1024)} KB).`);
}
const generatedModule = `// Generated by scripts/embed-web-app.mjs. Do not edit by hand.\nexport const embeddedOutlyrideHtml = ${JSON.stringify(html)};\n`;
await writeFile(resolve(expoDirectory, 'embeddedOutlyride.ts'), generatedModule);

console.log(
  `Embedded Outlyride UI (${Math.round(htmlBytes / 1024)} KB HTML, ${embeddedImageCount} offline images).`,
);
